import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { formatCurrency } from '../utils/formatCurrency';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const Statements = () => {
  const { user } = useAuth();
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchTransactions = async (pageNum = 1) => {
    try {
      setLoading(true);
      const config = { headers: { Authorization: `Bearer ${user.token}` } };
      // Using the paginated endpoint we created
      const res = await axios.get(`http://localhost:5000/api/transactions?page=${pageNum}&limit=10`, config);
      
      setTransactions(res.data.data);
      setTotalPages(res.data.pages);
      setPage(pageNum);
    } catch (err) {
      console.error("Error", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTransactions(1);
  }, [user]);

  const generatePDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text('Bank Statement', 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated by: ${user.name}`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 36);

    const tableColumn = ["Date", "Txn ID", "Account", "Type", "Amount", "Balance"];
    const tableRows = [];

    transactions.forEach(txn => {
      const txnData = [
        new Date(txn.createdAt || txn.date).toLocaleString('en-IN'),
        txn.id,
        txn.accountNumber,
        txn.transactionType,
        formatCurrency(txn.amount),
        formatCurrency(txn.balanceAfterTransaction)
      ];
      tableRows.push(txnData);
    });

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 45,
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [0, 82, 204] } // Primary blue
    });

    doc.save(`statement_${user.name.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);
  };

  return (
    <div>
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h3 className="text-primary fw-bold mb-0">Account Statements</h3>
        <button className="btn btn-outline-primary rounded-pill fw-bold" onClick={generatePDF}>
          <i className="bi bi-file-earmark-pdf-fill me-2"></i> Download PDF
        </button>
      </div>
      
      <div className="card shadow-sm border-0">
        <div className="card-body p-0">
          <div className="table-responsive">
            <table className="table table-hover align-middle mb-0">
              <thead className="table-light">
                <tr>
                  <th>Date</th>
                  <th>Transaction ID</th>
                  <th>Account No.</th>
                  <th>Type</th>
                  <th>Description</th>
                  <th>Amount</th>
                  <th>Balance</th>
                </tr>
              </thead>
              <tbody>
                {transactions.map(txn => (
                  <tr key={txn.id || txn._id}>
                    <td>{new Date(txn.createdAt || txn.date).toLocaleString('en-IN')}</td>
                    <td className="text-muted text-sm">{txn.id || txn._id}</td>
                    <td className="fw-bold">{txn.accountNumber}</td>
                    <td>
                      <span className={`badge ${['Deposit', 'Interest Credit'].includes(txn.transactionType) ? 'bg-success' : 'bg-danger'}`}>
                        {txn.transactionType}
                      </span>
                    </td>
                    <td className="text-muted">{txn.description || '-'}</td>
                    <td className={`fw-bold ${['Deposit', 'Interest Credit'].includes(txn.transactionType) ? 'text-success' : 'text-danger'}`}>
                      {['Deposit', 'Interest Credit'].includes(txn.transactionType) ? '+' : '-'}{formatCurrency(txn.amount)}
                    </td>
                    <td className="text-muted">{formatCurrency(txn.balanceAfterTransaction)}</td>
                  </tr>
                ))}
                {transactions.length === 0 && !loading && (
                  <tr><td colSpan="7" className="text-center py-4">No transactions found.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
        {totalPages > 1 && (
          <div className="card-footer bg-white border-0 py-3">
            <nav>
              <ul className="pagination justify-content-center mb-0">
                <li className={`page-item ${page === 1 ? 'disabled' : ''}`}>
                  <button className="page-link" onClick={() => fetchTransactions(page - 1)}>Previous</button>
                </li>
                {[...Array(totalPages)].map((_, i) => (
                  <li key={i} className={`page-item ${page === i + 1 ? 'active' : ''}`}>
                    <button className="page-link" onClick={() => fetchTransactions(i + 1)}>{i + 1}</button>
                  </li>
                ))}
                <li className={`page-item ${page === totalPages ? 'disabled' : ''}`}>
                  <button className="page-link" onClick={() => fetchTransactions(page + 1)}>Next</button>
                </li>
              </ul>
            </nav>
          </div>
        )}
      </div>
    </div>
  );
};

export default Statements;
